### ISSUE TITLE
import error running readme

### ISSUE THREAD

**Issue by ghost** [FORTH-ModelBasedTracker/HandTracker#20]
Hello,

I received the following import error. Note, I am currently running libfreenect (versus libfreenect 2) so that may be a problem. However, it is unclear if that is causing python to throw the error.

MBV_LIBS Environment variable should point to the MBV libraries folder.
MBV_LIBS /home/rabadi/software/mbv
Setting LD_LIBRARY_PATH and PYTHONPATH
Running the Single Hand Tracker script...
Traceback (most recent call last):
  File "src/SingleHandTracking.py", line 8, in <module>
    import PyMBVCore as Core
ImportError: /path/to/mbv/libs/libCore.so: undefined symbol: _ZN2cv9ExceptionC1EiRKSsS2_S2_i

Thanks!

**Comment by padeler** [comment]
Hello,

You need openni to use the tracker (not libfreenect). From the import error it looks like the issue is related to the opencv version. Please make sure you have the correct dependencies installed. Check the [readme.md](https://github.com/FORTH-ModelBasedTracker/HandTracker/blob/master/README.md) for more information.
