### ISSUE TITLE
Further application using this lib

### ISSUE THREAD

**Issue by YuYangguang** [FORTH-ModelBasedTracker/HandTracker#35]
I have run the demo of this lib. But this lib is not open source,which hinder the further development. And this demo is just to track the hand. Do you have further application of this lib, such as gesture recognization?

**Comment by nkyriazis** [comment]
The source is not provided, but we do provide complete python bindings over the entire codebase which we, too, use to build applications with. Understandably, lack of documentation does not make this easy, but, that's why we're here for.  :)

We are looking forward to helping users build applications on top of our HandTracker. If you have a specific application in mind and wonder whether our libs can help, please do ask, and maybe you'll find that you can indeed be helped.
