### ISSUE TITLE
Very slow startup even with increasing cache size

### ISSUE THREAD

**Issue by MarkusEich** [FORTH-ModelBasedTracker/HandTracker#7]
After starting the runme.sh script it takes EVERY  time around 3! minutes until the window appears. 
Even after setting the CUDA_CACHE_MAXSIZE=2147483648, as recommended.

Is there any way to speed up the process?

System used: Ubuntu 15.10, CUDA 7.5, NVIDIA GTX860M (4GB RAM), 16GB RAM, Intel I7 CPU

**Comment by padeler** [comment]
The slow startup speed is due to the JIT compilation of the CUDA code. Since the generated binaries are bigger than the default cache, the workaround is to increase the max cuda cache size (this is what nvidia also suggests). Maybe your cache size is set somewhere else? Try setting it in your `.bashrc` file

**Comment by MarkusEich** [comment]
Checked setting with env. Gives a chache size of CUDA_CACHE_MAXSIZE=2147483648. Even tried with double size (4GB). The folder ~/.nv is there and readable/writable. 

I read that JIT compilation takes place if the host architecture is different from the compile architecture. Maybe if all features are compiled for all architectures (i.e. sm_10,sm_13,sm_20,sm_30,sm_35), the JIT will not be necessary  (but I might be wrong).

Anyone else having the slow start-up issue?

**Comment by MarkusEich** [comment]
Solved. I had to set explicitly export CUDA_CACHE_DISABLE=0. Thought it would have been enabled by default. First run now takes 2 minutes, second run 2 seconds.
