### ISSUE TITLE
Recognition Problem with the HandObjectTracking demo

### ISSUE THREAD

**Issue by zhuzilin** [FORTH-ModelBasedTracker/HandTracker#75]
![image](https://user-images.githubusercontent.com/10428324/30229618-a5008c7c-94b0-11e7-973e-e7a92248e1a7.png)
I wonder if this kind of situation is normal. Or there are other things that I need to adjust?

**Comment by padeler** [comment]
Track loss can happen with any configuration of the model based tracker. Even more so with the joint hand-object tracking.  Since the library does not offer some form of automatic re-initialization, you have to detect track loss and re-initialize using another method.

Regarding the hand-object tracking example, it should track the test sequence with the parameters (budget, variances, etc) set in the corresponding python script.
